### PR TITLE
Update meta files

### PR DESCRIPTION
**Pull request by t0d0r**
message is set to "VarnaLab is a nice place, join us"

### CODE REVIEW

**Comment by t0d0r** [comment]
@simov, merge, merge :)

**Comment by simov** [comment]
The initial message is kind of nice, I get your idea, here are my concerns:

1. This change makes the alphabet very small - only a few symbols
2. Each message (matrix drop) is identical
3. I want the matrix to look more natural - random

I'm thinking about something better - display only 0 and 1 for the initial animation and then start random string drops using the cyrillic alphabet + the 0 and 1 here and there. I have something similar implemented.

What do you think?

**Comment by simov** [comment]
https://youtu.be/H_ko9Gr8SQs

/cc @t0d0r 

That was my idea. Although the rain drop animation should be slower IMO.

**Comment by simov** [comment]
I just compiled all of my tests in this **[demo](https://simov.github.io/matrix/)**.
Check it out!

**Comment by simov** [comment]
Rebased and merged only the `clean` command, also added `.editorconfig` file. This should fix the white spaces next time.

As for the initial matrix message I'll try to implement the ascii art that I showed you earlier. :+1:

**Pull request merged**
